In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [13]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [15]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [17]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [18]:
dframe1

X         Y         Z
0  0.774193 -0.257910 -0.666635
1 -0.593481 -0.408467  1.010532
2  0.160778 -0.370439 -0.563624
3  0.307096  1.727123  1.956716

In [19]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [21]:
dframe2

Y         Q         X
0  1.219443 -0.662477 -1.127002
1  2.243997 -0.950066  0.225589
2  0.208450 -0.949468 -0.540492

In [22]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.774193 -0.257910 -0.666635
1       NaN -0.593481 -0.408467  1.010532
2       NaN  0.160778 -0.370439 -0.563624
3       NaN  0.307096  1.727123  1.956716
0 -0.662477 -1.127002  1.219443       NaN
1 -0.950066  0.225589  2.243997       NaN
2 -0.949468 -0.540492  0.208450       NaN

In [24]:
pd.concat([dframe1,dframe2],ignore_index=True) 
#indexを無視して新しくindexの数字をふる

Q         X         Y         Z
0       NaN  0.774193 -0.257910 -0.666635
1       NaN -0.593481 -0.408467  1.010532
2       NaN  0.160778 -0.370439 -0.563624
3       NaN  0.307096  1.727123  1.956716
4 -0.662477 -1.127002  1.219443       NaN
5 -0.950066  0.225589  2.243997       NaN
6 -0.949468 -0.540492  0.208450       NaN