In [1]:
import numpy as np

In [2]:
my_list1=[1,2,3,4]

In [3]:
mu_array1=np.array(my_list)

NameError: name 'my_list' is not defined

In [4]:
my_array1=np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2=[11,22,33,44]

In [8]:
my_lists=[my_list1,my_list2]

In [10]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [14]:
my_array2=np.array(my_lists)

In [17]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [19]:
my_array2.shape

(2, 4)

In [20]:
my_array2.dtype

dtype('int64')

In [24]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [27]:
my_zeros=np.zeros(5)

In [28]:
my_zeros.dtype

dtype('float64')

In [29]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [30]:
np.empty(())

array(1.0)

In [31]:
np.empty((3,4))

array([[  0.00000000e+000,  -1.49166824e-154,   2.96439388e-323,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          8.34402697e-309]])

In [32]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [33]:
np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])