In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.76445163,  0.01550666, -1.27289839,  1.40679221, -0.26255074,
       -0.1641496 ,  0.48729785,  0.94893441,  0.54061398,  0.79817923])

In [9]:
B = np.random.randn(10)

In [10]:
B

array([-1.99732421, -0.64274051,  0.09231202, -0.40770347, -0.74060664,
       -0.18772632,  0.4223889 , -0.18642727,  0.14534853, -0.51381324])

In [11]:
np.add(A,B)

array([-2.76177584, -0.62723385, -1.18058637,  0.99908873, -1.00315738,
       -0.35187592,  0.90968675,  0.76250714,  0.68596251,  0.28436599])

In [12]:
np.maximum(A,B)

array([-0.76445163,  0.01550666,  0.09231202,  1.40679221, -0.26255074,
       -0.1641496 ,  0.48729785,  0.94893441,  0.54061398,  0.79817923])