In [1]:
import numpy as np

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[0:5]=100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [14]:
arr=np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_arr=arr[0:6]

In [19]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_arr[:]=99

In [21]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy=arr.copy()

In [24]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy[:]=50

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [35]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[1]

array([20, 25, 30])

In [39]:
arr_2d[1][0]

20

In [40]:
arr_2d[1,0]

20

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
arr_2d[2]

array([35, 40, 45])

In [44]:
arr_2d[2:1]

array([], shape=(0, 3), dtype=int64)

In [45]:
arr_2d[2:]

array([[35, 40, 45]])

In [46]:
arr2d=np.zeros((10,10))

In [47]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [48]:
arr_length=arr2d.shape[1]

In [51]:
 for i in range(arr_length):
        arr2d[i]=i

In [52]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [55]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])